var var1 = 14;
var var2 = 18;
addition = var1 + var2;
subtraction = var1 - var2;
multiplication = var1 * var2;
division = var1 / var2;
modulo_division = var1 % var2;
console.log("Addition of two numbers " + addition);
console.log("Subtraction of two numbers " + subtraction);
console.log("Multiplication of two numbers is " + multiplication);
console.log("Division of two numbers " + division);
console.log("Modulus of two numbers " + modulo_division);
